### ISSUE TITLE
Way of supporting client-based API

### ISSUE THREAD

**Issue by vicmosin** [zanella/nomad-api#12]
As you might know, there some API calls which must be performed against particular client (files list, file's content etc).

What do you think about having [such feature](https://github.com/smoope/nomad-api/blob/feature/members/src/main/java/io/github/zanella/nomad/NomadClient.java#L32) in your lib (improvements like caching must be added)? 
The call will be `client.node(someNodeId).v1.client.getFileList(path)`.

In general it could be done at client side as well, but then it will have to deal with managing pool of such clients.. While doing it in SDK makes it much easier since the pool of members already part of client itself.

**Comment by zanella** [comment]
I am actually a bystander as of now really, you and @donovanmuller are commiting new stuff :-)

I'll read up about it later.

(Looking at your code actually made me remember to open this one #13 )

**Comment by vicmosin** [comment]
@donovanmuller any thoughts?

**Comment by donovanmuller** [comment]
@vicmosin I probably won't be using this functionality for my purposes but you're more than welcome to add 😄
