### ISSUE TITLE
/v1/client support

### ISSUE THREAD

**Issue by vicmosin** [zanella/nomad-api#6]
Do you plan to introduce it someday? 

https://www.nomadproject.io/docs/http/client-allocation-stats.html

**Comment by zanella** [comment]
There are no plans anymore to use nomad here, so no, I don't.

@donovanmuller: do you?

**Comment by donovanmuller** [comment]
@zanella I have no current use case for it, however thanks to @vicmosin (https://github.com/zanella/nomad-api/pull/8) support for it has been added.

**Comment by zanella** [comment]
ah!, can I close this one then ?

**Comment by vicmosin** [comment]
Yeah, it was me.. I asked it, but then realized that it's much faster to implement it))
